name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libgl-dev libglfw3-dev

    - name: Setup MSYS2 for Windows
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-glfw
          mingw-w64-x86_64-glew
          make

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: brew install glfw3 glew

    - name: Build (Linux)
      run: make
      shell: bash
      if: matrix.os == 'ubuntu-latest'

    - name: Build (MSYS2 on Windows)
      run: make
      shell: msys2 {0}
      if: matrix.os == 'windows-latest'

    - name: Build (macOS)
      run: make
      shell: bash
      if: matrix.os == 'macos-latest'

    - name: Run tests
      run: cd tests && make
      shell: bash
      if: matrix.os == 'ubuntu-latest'

    - name: Run tests (MSYS2 on Windows)
      run: cd tests && make
      shell: msys2 {0}
      if: matrix.os == 'windows-latest'

    - name: Run tests (macOS)
      run: cd tests && make
      shell: bash
      if: matrix.os == 'macos-latest'

    - name: Run hc
      run: cd utils/hc && make
      shell: bash
      if: matrix.os == 'ubuntu-latest'

    - name: Run hc (MSYS2 on Windows)
      run: cd utils/hc && make
      shell: msys2 {0}
      if: matrix.os == 'windows-latest'

    - name: Run hc (macOS)
      run: cd utils/hc && make
      shell: bash
      if: matrix.os == 'macos-latest'
